export const descJson = [
  {
    id: 1,
    desc: "CUSTOMER_LIST_HELP",
    link: "/help",
    path: "/customer/customer-list",
  },
  {
    id: 2,
    desc: "CUSTOMER_GROUPS_HELP",
    link: "/help",
    path: "/customer/customer-group",
  },
  {
    id: 3,
    desc: "CUSTOMER_CLASSES_HELP",
    link: "/help",
    path: "/customer/customer-class",
  },
  {
    id: 4,
    desc: "CUSTOMER_DIVISIONS_HELP",
    link: "/help",
    path: "/customer/customer-division",
  },
  {
    id: 5,
    desc: "DISTRIBUTION_CHANNELS_HELP",
    link: "/help",
    path: "/customer/distribution-channel",
  },
  {
    id: 6,
    desc: "TAX_MATRIX_HELP",
    link: "/help",
    path: "/taxconfiguration/tax-matrix",
  },
  {
    id: 7,
    desc: "TAX_GROUP_HELP",
    link: "/help",
    path: "/taxconfiguration/tax-group",
  },
  {
    id: 8,
    desc: "PRODUCT_TAX_GROUP_HELP",
    link: "/help",
    path: "/taxconfiguration/product-tax-group",
  },
  {
    id: 9,
    desc: "TRANSLATIONS_WEB_HELP",
    link: "/help",
    path: "/translations/web",
  },
  {
    id: 10,
    desc: "TRANSLATIONS_MOBILE_HELP",
    link: "/help",
    path: "/translations/mobile",
  },
  {
    id: 11,
    desc: "PRODUCT_GROUPS_HELP",
    link: "/help",
    path: "/products/products-groups",
  },
  {
    id: 12,
    desc: "PRODUCT_DIVISIONS_HELP",
    link: "/help",
    path: "/products/products-divisions",
  },
  {
    id: 13,
    desc: "PRODUCT_BRANDS_HELP",
    link: "/help",
    path: "/products/products-brands",
  },
  {
    id: 14,
    desc: "PRODUCT_FAMILY_HELP",
    link: "/help",
    path: "/products/products-family",
  },
  {
    id: 15,
    desc: "PRODUCT_CATEGORY_HELP",
    link: "/help",
    path: "/product/product-category",
  },
  {
    id: 16,
    desc: "PRODUCT_SUBCATEGORY_HELP",
    link: "/help",
    path: "/product/product-subcategory",
  },
  {
    id: 17,
    desc: "PRODUCT_PRICE_LIST_HELP",
    link: "/help",
    path: "/product/product-price-list",
  },
  {
    id: 18,
    desc: "PRODUCT_TYPE_HELP",
    link: "/help",
    path: "/product/product-type",
  },
  {
    id: 19,
    desc: "CUSTOM_FIELDS_CUSTOMERS_HELP",
    link: "/help",
    path: "/customfields/customers",
  },
  {
    id: 20,
    desc: "CUSTOM_FIELDS_PRODUCTS_HELP",
    link: "/help",
    path: "/customfields/products",
  },
  {
    id: 21,
    desc: "CUSTOM_FIELDS_STORES_HELP",
    link: "/help",
    path: "/customfields/stores",
  },
  {
    id: 22,
    desc: "CUSTOM_FIELDS_SALES_TRANSACTION_HELP",
    link: "/help",
    path: "/customfields/salesmen",
  },
  {
    id: 23,
    desc: "CUSTOM_FIELDS_SALES_TRANSACTION_HELP",
    link: "/help",
    path: "/customfields/sales-transaction",
  },
  {
    id: 24,
    desc: "PAYMENT_TERMS_HELP",
    link: "/help",
    path: "/customer/payment-terms",
  },
  {
    id: 25,
    desc: "PRODUCTS_SERIAL_NUMBER_HELP",
    link: "/help",
    path: "/products/serial-number",
  },
];
