export const defaultValues = {
  id: "",
  active: true,
  altName: "",
  code: "Auto Generated",
  name: "",
  terminalNum: "",
  deviceType: "",
  deviceOS: "",
  deviceBrand: "",
  imeiNumber: "",
  companyId: "",
  createdOn: "",
  createdBy: "",
  updatedOn: "",
  updatedBy: "",
  status: "",
};
