export const defaultValues = {
  id: "",
  active: true,
  altName: "",
  code: "Auto Generated",
  name: "",
  totalCustomers: "",
  tenantId: "",
  companyId: "",
  createdOn: "",
  createdBy: "",
  updatedOn: "",
  updatedBy: "",
  externalReference: "",
};
