// ** Type import
import { VerticalNavItemsType } from "src/@core/layouts/types";
import { PiListNumbers } from "react-icons/pi";

const navigation = (): VerticalNavItemsType => {
  return [
    {
      title: "DASHBOARDS",
      icon: "tabler:layout-grid",
      module: "dashboards",
      // badgeContent: 'new',
      // badgeColor: 'error',
      children: [
        {
          title: "OVERVIEW",
          path: "/dashboards/analytics",
          action: "read",
          subject: "acl-page",
          module: "dashboards",
        },
        {
          title: "SALES",
          path: "/dashboards/crm",
          action: "read",
          subject: "acl-page",
          module: "dashboards",
        },
        {
          title: "INVENTORY_DASHBOARD",
          path: "/dashboards/ecommerce",
          action: "read",
          subject: "acl-page",
          module: "dashboards",
        },
      ],
    },
    {
      title: "CUSTOMERS",
      icon: "tabler:users",
      module: "customer",
      children: [
        {
          path: "/customer/customer-list",
          action: "read",
          subject: "acl-page",
          title: "CUSTOMER_LIST",
          module: "customer",
        },
        {
          path: "/customer/customer-group",
          action: "read",
          subject: "acl-page",
          title: "CUSTOMER_GROUP",
          module: "customer",
        },
        {
          path: "/customer/customer-class",
          action: "read",
          subject: "acl-page",
          title: "CUSTOMER_CLASS",
          module: "customer",
        },
        {
          title: "CUSTOMER_DIVISION",
          path: "/customer/customer-division",
          module: "customer",
        },
        {
          title: "DISTRIBUTION_CHANNEL",
          path: "/customer/distribution-channel",
          module: "customer",
        },
        {
          title: "ATTRIBUTES",
          path: "/customer/attributes",
          action: "read",
          subject: "acl-page",
          module: "customer",
        },
        // {
        //   title: "CUSTOM_FIELDS",
        //   path: "/customfields/customers",
        //   module: "customer",
        // },
        {
          title: "PAYMENT_TERMS",
          path: "/customer/payment-terms",
          module: "customer",
        },
        {
          title: "PAYMENT_METHODS",
          path: "/customer/payment-methods",
          action: "read",
          subject: "acl-page",
          module: "customer",
        },
      ],
    },
    {
      title: "PRODUCTS",
      icon: "tabler:box",
      module: "products",
      children: [
        {
          path: "/products/products-list",
          action: "read",
          subject: "acl-page",
          title: "PRODUCT_LIST",
          module: "products",
        },
        {
          path: "/products/products-divisions",
          title: "PRODUCTS_DIVISIONS",
          module: "products",
        },
        {
          path: "/products/products-brands",
          title: "PRODUCTS_BRANDS",
          module: "products",
        },
        {
          path: "/products/product-category",
          action: "read",
          subject: "acl-page",
          title: "PRODUCT_CATEGORY",
          module: "products",
        },
        {
          path: "/products/product-subcategory",
          action: "read",
          subject: "acl-page",
          title: "PRODUCT_SUBCATEGORY",
          module: "products",
        },
        {
          path: "/products/products-family",
          title: "PRODUCTS_FAMILY",
          module: "products",
        },
        {
          path: "/products/products-groups",
          title: "PRODUCTS_GROUPS",
          module: "products",
        },
        {
          path: "/products/product-type",
          action: "read",
          subject: "acl-page",
          title: "PRODUCT_TYPE",
          module: "products",
        },
        {
          title: "PRODUCTS_BATCH",
          path: "/products/products-batch",
          module: "products",
        },
        {
          title: "SERIAL_NUMBERS",
          path: "/products/serial-number",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
        {
          title: "ATTRIBUTES",
          path: "/products/attributes",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
        {
          title: "HIERARCHICAL_VIEW",
          path: "/products/hierarchical-view",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
        {
          title: "UNIT_OF_MEASURE",
          path: "/products/unit-of-measure",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
        {
          title: "UOM_CONVERSION",
          path: "/products/uom-conversion",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
        {
          title: "CUSTOM_FIELDS",
          path: "/customfields/products",
          module: "products",
        },
        {
          title: "CATALOGUES_MASTER",
          path: "/products/catalogues-master",
          action: "read",
          subject: "acl-page",
          module: "products",
        },
      ],
    },
    // {
    //   title: "USER_MASTER",
    //   path: "/user-master",
    //   icon: "tabler:users-group",
    //   module: "user-master",
    // },
    {
      title: "TAX_CONFIGURATION",
      icon: "tabler:receipt-tax",
      module: "taxconfiguration",
      children: [
        {
          path: "/taxconfiguration/basic-tax-setup",
          action: "read",
          subject: "acl-page",
          title: "BASIC_TAX_SETUP",
          module: "taxconfiguration",
        },
        {
          title: "ADVANCED_TAX",
          path: "/taxconfiguration/advance-tax",
          action: "read",
          subject: "acl-page",
          module: "taxconfiguration",
        },
      ],
    },
    {
      title: "CUSTOMER_PROFILE",
      path: "/customer-profile",
      icon: "tabler:id",
      module: "customer-profile",
      action: "read",
      subject: "acl-page",
    },
    {
      title: "PRICE_LIST",
      icon: "tabler:list-numbers",
      path: "/pricelist/price-list",
      module: "pricelist",
    },
    {
      title: "VENDORS",
      action: "read",
      subject: "acl-page",
      icon: "tabler:building-store",
      module: "vendors",
      children: [
        {
          title: "VENDORS",
          path: "/vendors/vendors",
          action: "read",
          subject: "acl-page",
          module: "vendors",
        },
        {
          title: "GROUPS",
          path: "/vendors/groups",
          action: "read",
          subject: "acl-page",
          module: "vendors",
        },
        {
          title: "CLASSES",
          path: "/vendors/classes",
          action: "read",
          subject: "acl-page",
          module: "vendors",
        },
        {
          title: "DIVISIONS",
          path: "/vendors/divisions",
          action: "read",
          subject: "acl-page",
          module: "vendors",
        },
        {
          title: "PAYMENT_TERMS",
          path: "/vendors/payment-terms",
          action: "read",
          subject: "acl-page",
          module: "vendors",
        },
      ],
    },
    {
      title: "PROMOTIONS",
      icon: "tabler:speakerphone",
      action: "read",
      subject: "acl-page",
      module: "promotions",
      children: [
        {
          title: "PROMOTIONS",
          path: "/promotions/promotions",
          action: "read",
          subject: "acl-page",
          module: "promotions",
        },
        {
          title: "ADVANCED_PRICING",
          path: "/promotions/advanced-pricing",
          action: "read",
          subject: "acl-page",
          module: "promotions",
        },
        {
          title: "EXTERNAL_PROMOTIONS",
          path: "/promotions/external-promotions",
          action: "read",
          subject: "acl-page",
          module: "promotions",
        },
      ],
    },

    {
      title: "POINT_OF_SALES",
      icon: "tabler:device-desktop-analytics",
      action: "read",
      subject: "acl-page",
      module: "point-of-sales",
      children: [
        {
          title: "SALES",
          path: "/point-of-sales/sales",
          action: "read",
          subject: "acl-page",
          module: "point-of-sales",
        },
        {
          title: "RETURN",
          path: "/point-of-sales/return",
          action: "read",
          subject: "acl-page",
          module: "point-of-sales",
        },
      ],
    },

    {
      title: "KIOSK",
      action: "read",
      icon: "tabler:devices-2",
      subject: "acl-page",
      module: "kiosk",
      children: [
        {
          title: "SELF_CHECKOUT",
          path: "/kiosk/self-checkout",
          action: "read",
          subject: "acl-page",
          module: "kiosk",
        },
        {
          title: "SETTINGS",
          path: "/kiosk/settings",
          action: "read",
          subject: "acl-page",
          module: "kiosk",
        },
      ],
    },

    {
      title: "PURCHASE",
      action: "read",
      icon: "tabler:report",
      subject: "acl-page",
      module: "purchase",
      children: [
        {
          title: "PURCHASE_ORDER",
          path: "/purchase/purchase-order",
          action: "read",
          subject: "acl-page",
          module: "purchase",
        },
        {
          title: "PURCHASE_INVOICE",
          path: "/purchase/purchase-invoice",
          action: "read",
          subject: "acl-page",
          module: "purchase",
        },
        {
          title: "RETURN_ORDER",
          path: "/purchase/return-order",
          action: "read",
          subject: "acl-page",
          module: "purchase",
        },
      ],
    },

    {
      title: "INVENTORY",
      action: "read",
      icon: "tabler:stack-2",
      subject: "acl-page",
      module: "inventory",
      children: [
        {
          title: "TRANSFER_ORDERS",
          path: "/inventory/transfer-order",
          action: "read",
          subject: "acl-page",
          module: "inventory",
        },
        {
          title: "ADJUSTMENTS",
          path: "/inventory/adjustments",
          action: "read",
          subject: "acl-page",
          module: "inventory",
        },
        {
          title: "COUNTING",
          path: "/inventory/counting",
          action: "read",
          subject: "acl-page",
          module: "inventory",
        },
        {
          title: "GOODS_ISSUE",
          path: "/inventory/goods-issue",
          action: "read",
          subject: "acl-page",
          module: "inventory",
        },
      ],
    },

    {
      title: "REPORTS",
      action: "read",
      icon: "tabler:report-search",
      subject: "acl-page",
      module: "reports",
      children: [
        {
          title: "SALES",
          action: "read",
          subject: "acl-page",
          module: "sales",
          children: [
            {
              title: "ORDER_HISTORY",
              path: "/reports/sales/order-history",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
            {
              title: "INVOICE_HISTORY",
              path: "/reports/sales/invoice-history",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
            {
              title: "CASH_IN_OUT",
              path: "/reports/sales/cash-in-out",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
            {
              title: "SALES_BY_PRODUCTS",
              path: "/reports/sales/sales-by-products",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
            {
              title: "SALES_BY_PAYMENT_METHODS",
              path: "/reports/sales/sales-by-payment-methods",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
            {
              title: "INVOICE_HISTORY2",
              path: "/reports/sales/invoice-history2",
              action: "read",
              subject: "acl-page",
              module: "sales",
            },
          ],
        },
        {
          title: "INVENTORY_REPORTS",
          action: "read",
          subject: "acl-page",
          module: "inventory-reports",
          children: [
            {
              title: "ON_HAND_STOCK",
              path: "/reports/inventory/on-hand-stock",
              action: "read",
              subject: "acl-page",
              module: "inventory-reports",
            },
            {
              title: "STOCK_TRANSACTIONS",
              path: "/reports/inventory/stock-transactions",
              action: "read",
              subject: "acl-page",
              module: "inventory-reports",
            },
            {
              title: "INVENTORY_AGEING",
              path: "/reports/inventory/inventory-ageing",
              action: "read",
              subject: "acl-page",
              module: "inventory-reports",
            },
            {
              title: "TRANSFER_ORDERS",
              path: "/reports/inventory/transfer-orders",
              action: "read",
              subject: "acl-page",
              module: "inventory-reports",
            },
          ],
        },
        {
          title: "PURCHASING",
          action: "read",
          subject: "acl-page",
          module: "purchasing",
          children: [
            {
              title: "PURCHASE_HISTORY",
              path: "/reports/purchasing/purchase-history",
              action: "read",
              subject: "acl-page",
              module: "purchasing",
            },
            {
              title: "INVOICE_HISTORY",
              path: "/reports/purchasing/invoice-history",
              action: "read",
              subject: "acl-page",
              module: "purchasing",
            },
            {
              title: "PURCHASE_BY_PRODUCTS",
              path: "/reports/purchasing/purchase-by-products",
              action: "read",
              subject: "acl-page",
              module: "purchasing",
            },
            {
              title: "PRODUCTS_BY_VENDOR",
              path: "/reports/purchasing/products-by-vendor",
              action: "read",
              subject: "acl-page",
              module: "purchasing",
            },
            {
              title: "VENDOR_HISTORY",
              path: "/reports/purchasing/vendor-history",
              action: "read",
              subject: "acl-page",
              module: "purchasing",
            },
          ],
        },
      ],
    },

    {
      title: "GENERAL_SETUP",
      action: "read",
      icon: "tabler:settings",
      subject: "acl-page",
      module: "general-setup",
      children: [
        {
          title: "ORG_GROUP",
          path: "/general-setup/org-group",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "COMPANIES",
          path: "/general-setup/companies",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "LEGAL_ENTITIES",
          path: "/general-setup/legal-entities",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "BUSINESS_UNITS",
          path: "/general-setup/business-units",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "STORES",
          path: "/general-setup/stores",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "COUNTRIES",
          path: "/general-setup/countries",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "REGIONS",
          path: "/general-setup/regions",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "CITIES",
          path: "/general-setup/cities",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "DISTRICTS",
          path: "/general-setup/districts",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "CURRENCIES",
          path: "/general-setup/currencies",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "HIERARCHICAL_VIEW",
          path: "/general-setup/hierarchical-view",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
        {
          title: "NUMBER_SEQUENCES",
          path: "/general-setup/number-sequences",
          action: "read",
          subject: "acl-page",
          module: "general-setup",
        },
      ],
    },

    {
      title: "USERS_AND_ROLES",
      action: "read",
      icon: "tabler:user-check",
      subject: "acl-page",
      module: "users-roles",
      children: [
        {
          title: "USER_MASTER",
          path: "/users-roles/user-master",
          module: "users-roles",
        },
        {
          title: "ROLES",
          path: "/users-roles/roles",
          module: "users-roles",
        },
      ],
    },

    {
      title: "SETTINGS",
      icon: "material-symbols:settings-outline",
      action: "read",
      subject: "acl-page",
      module: "settings",
      children: [
        {
          title: "TRANSLATIONS",
          action: "read",
          subject: "acl-page",
          module: "translations",
          children: [
            {
              title: "WEB",
              path: "/translations/web",
              module: "translations",
            },
            {
              title: "MOBILE",
              path: "/translations/mobile",
              module: "translations",
            },
          ],
        },
        {
          title: "LAYOUT",
          action: "read",
          subject: "acl-page",
          module: "layout",
          children: [
            {
              title: "SALES_INVOICE",
              module: "layout",
              path: "/invoicetemplate",
              action: "read",
              subject: "acl-page",
            },
            {
              title: "RETURN_INVOICE",
              path: "/settings/layouts/return-invoice",
              action: "read",
              subject: "acl-page",
              module: "layout",
            },
            {
              title: "TRANSFER_ORDER",
              path: "/settings/layouts/transfer-orders",
              action: "read",
              subject: "acl-page",
              module: "layout",
            },
            {
              title: "PURCHASE_ORDER",
              path: "/settings/layouts/purchase-order",
              action: "read",
              subject: "acl-page",
              module: "layout",
            },
            {
              title: "PURCHASE_INVOICE",
              path: "/settings/layouts/purchase-invoice",
              action: "read",
              subject: "acl-page",
              module: "layout",
            },
          ],
        },
        {
          title: "INTEGRATIONS",
          action: "read",
          subject: "acl-page",
          module: "integration",
          children: [
            {
              title: "ERP",
              path: "/settings/integration/erp",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
            {
              title: "ECOMMERCE",
              path: "/settings/integration/ecommerce",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
            {
              title: "THIRD_PARTY",
              path: "/settings/integration/third-party",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
            {
              title: "SMS",
              path: "/settings/integration/sms",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
            {
              title: "EMAIL",
              path: "/settings/integration/email",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
            {
              title: "WHATSAPP",
              path: "/settings/integration/whatsapp",
              action: "read",
              subject: "acl-page",
              module: "integration",
            },
          ],
        },
        {
          title: "AUDIT_LOG",
          path: "/audit-log",
          action: "read",
          subject: "acl-page",
          module: "settings",
        },
        {
          title: "WORKFLOWS",
          action: "read",
          subject: "acl-page",
          module: "workflows",
          children: [
            {
              title: "APPROVAL_TEMPLATES",
              path: "/workflows/approval-templates",
              action: "read",
              subject: "acl-page",
              module: "workflows",
            },
            {
              title: "COMMITTEE_GROUPS",
              path: "/workflows/committee-groups",
              action: "read",
              subject: "acl-page",
              module: "workflows",
            },
            {
              title: "EXTERNAL_COMMITTEE",
              path: "/workflows/external-committee",
              action: "read",
              subject: "acl-page",
              module: "workflows",
            },
            {
              title: "DELEGATION_PREFERENCES",
              path: "/workflows/delegation-preferences",
              action: "read",
              subject: "acl-page",
              module: "workflows",
            },
            {
              title: "REPORTS",
              path: "/workflows/reports",
              action: "read",
              subject: "acl-page",
              module: "workflows",
            },
          ],
        },
      ],
    },
  ];
};

export default navigation;
